version: 2.1
owner: loody

orbs:
  python: circleci/python@0.2.1

jobs:
  build-and-test:
    executor: python/default
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - python/save-cache
      - run:
          command: ./UWUDDoSerIPag.py --help
          name: UWUDDOSERIPAG

workflows:
  main:
    jobs:
      - build-and-test
